### ISSUE TITLE
Maximum concealment on a gun is 30 even though it is not

### ISSUE THREAD

**Issue by DrPHDCat** [BlakeIsMyWaifu/PaydayBuilder#9]
Some guns like Bernetti 9 can reach up to 34 concealment making the decetion rate incorrect since pd2.dev does not allow 31+ concealment

**Comment by JoelDohmKaratjas** [comment]
Thank you for letting me know. I don't know why i thought concealment was limited to 30 but that was my mistake. I've fixed it in https://github.com/BlakeIsMyWaifu/PaydayBuilder/commit/bc4b066b487588c9300bb53efc8021342f14df1d but won't merge to master until i've done other fixes.
